"""
Rebuild Fig. 4 with the FPV main case.

Scientific scope
----------------
Fig. 4a explains grid-level FPV generation potential. The original HDF inputs
were generated with an FPV effective-area coefficient of 0.90. The main
main case uses 0.70 within the facade AOI, so capacity and generation are
converted by 0.70 / 0.90 before model fitting and plotting.

Fig. 4b reads the FPV=0.70, RPV=0.35 optimization results generated by
`Optimization/Multi_period_planning.py` and re-aggregates four zone-share
pies:
    upper-left  : Facade Area
    upper-right : Roof Area
    lower-left  : FPV carbon mitigation
    lower-right : RPV carbon mitigation

Definition choices for Fig. 4b
-------------------------------
1. Area is defined consistently for facade and roof as *main-case installable
   PV surface equivalent area*. Practically, this is reconstructed from the
   city main-case installable capacities and converted with one common nominal
   PV power density, so the zone shares are comparable across facade and roof.
   Using installable area is more consistent with the deployment and carbon-
   mitigation pies than using total geometric area.
2. FPV carbon mitigation is defined as the incremental mitigation from adding
   FPV on top of the optimized RPV pathway, i.e. (roof pathway carbon) minus
   (roof+facade pathway carbon), accumulated over all five planning periods.
3. RPV carbon mitigation is defined consistently as the mitigation of the
   optimized roof pathway relative to a no-PV baseline, accumulated over the
   same five planning periods. The no-PV baseline carbon is reconstructed from
   the saved grid loads and implied city-year carbon factors in the MAT files.

Run order
---------
1. Download the prepared public inputs or regenerate the installability tables.
2. python #Codes/Optimization/Multi_period_planning.py
3. python #Codes/Figures/Fig_new_4.py

PDF and 600 dpi PNG figures are written to:
    <repository>/#Codes/Figures/Figs_new/
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import warnings
from matplotlib.patches import Patch
import matplotlib
matplotlib.use("Agg")

import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
from matplotlib import rcParams
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import shap
import xgboost as xgb
from scipy.io import loadmat


# ------------------------- Main-case assumptions -------------------------

BASELINE_FPV_INSTALLABILITY = 0.90
MAIN_FPV_INSTALLABILITY = 0.70
FPV_MAIN_SCALE = MAIN_FPV_INSTALLABILITY / BASELINE_FPV_INSTALLABILITY
MAIN_CASE_ID = "RPV35_FPV70"
ABNORMAL_VOLUME_CITY_INDICES = {2, 6, 8, 69, 92, 97}

ZONE_ORDER = ("HnD", "HnS", "MnD", "MnS")
ZONE_COLORS = ["#69abd6", "#7cf9fddc", "#7cbb9e", "#8a99b8"]

RATIO_PLOT = 3
FIGWIDTH = 8.5 * RATIO_PLOT
FS = 8 * RATIO_PLOT
LW_AXIS = 0.8

# Use one common nominal PV power density for both roof and facade so that
# the "area" pies represent a consistent installable-PV-surface definition.
PV_POWER_DENSITY_W_M2 = 180.0

SCRIPT_DIR = Path(__file__).resolve().parent
REPOSITORY_ROOT = SCRIPT_DIR.parents[1]
DATA_ROOT = Path(os.environ.get("FPV_DATA_ROOT", REPOSITORY_ROOT / "##Data")).expanduser()
FIG_INPUT_DIR = Path(
    os.environ.get(
        "FPV_FIG_INPUT_DIR", DATA_ROOT / "Optimization" / "Fig_input_data"
    )
).expanduser()
DEFAULT_OPT_RESULTS_DIR = Path(
    os.environ.get(
        "FPV_OPT_RESULTS_DIR", DATA_ROOT / "Optimization" / "Planning_results"
    )
).expanduser()
DEFAULT_ML_RESULTS_DIR = Path(
    os.environ.get("FPV_ML_RESULTS_DIR", DATA_ROOT / "Evaluation" / "All_output")
).expanduser()
DEFAULT_CITY_FEATURE_DIR = Path(
    os.environ.get("FPV_CITY_FEATURE_DIR", DATA_ROOT / "Evaluation" / "All_input")
).expanduser()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Draw main-case Fig. 4 panels as PDF and PNG files."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=SCRIPT_DIR.parent,
        help="Repository root.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="PDF/PNG output directory. Default: <root>/Figures/Figs_new.",
    )
    parser.add_argument(
        "--opt-results-dir",
        type=Path,
        default=DEFAULT_OPT_RESULTS_DIR,
        help="Directory containing the FPV=0.70 optimization MAT files.",
    )
    parser.add_argument(
        "--ml-results-dir",
        type=Path,
        default=DEFAULT_ML_RESULTS_DIR,
        help="Directory containing City_statistic.xlsx, Grid_type, and Capacity files.",
    )
    parser.add_argument(
        "--city-feature-dir",
        type=Path,
        default=DEFAULT_CITY_FEATURE_DIR,
        help="Directory containing <city>_ALL_Featuers.npy for grid alignment.",
    )
    parser.add_argument(
        "--cluster-days",
        type=Path,
        default=None,
        help="Clu_days.npy path. Default: <root>/Figures/Fig_input_data/Clu_days.npy.",
    )
    args, _ = parser.parse_known_args()
    return args


def setup_style(figures_dir: Path) -> None:
    font_path = figures_dir / "arial.ttf"
    if font_path.exists():
        fm.fontManager.addfont(str(font_path))
        family = fm.FontProperties(fname=str(font_path)).get_name()
    else:
        family = "Arial"
        warnings.warn(
            f"{font_path} was not found; matplotlib will use its Arial fallback."
        )

    rcParams.update(
        {
            "font.family": family,
            "pdf.fonttype": 42,
            "axes.spines.right": False,
            "axes.spines.top": False,
            "axes.linewidth": 0.8,
            "legend.frameon": False,
        }
    )


def read_hdf(path: Path) -> pd.DataFrame:
    try:
        return pd.read_hdf(path, key="df")
    except ImportError as exc:
        raise ImportError(
            "PyTables is required to read the Fig_input_data HDF files. "
            "Install it in the Python environment with `pip install tables`."
        ) from exc


def infer_column(df: pd.DataFrame, candidates: list[str], label: str) -> str:
    for candidate in candidates:
        if candidate in df.columns:
            return candidate
    raise KeyError(
        f"Cannot infer {label} from {candidates}; available columns={list(df.columns)}"
    )


def value_column(df: pd.DataFrame, preferred: str, source: str) -> str:
    if preferred in df.columns:
        return preferred
    if len(df.columns) == 1:
        return df.columns[0]
    raise KeyError(
        f"{source} must contain '{preferred}' or exactly one value column; "
        f"available columns={list(df.columns)}"
    )


def hdf_metric_with_grid_ids(
    path: Path, preferred_value: str, output_value: str
) -> pd.DataFrame:
    raw = read_hdf(path)
    value_col = value_column(raw, preferred_value, path.name)
    flat = raw.reset_index()
    city_col = infer_column(flat, ["city", "City", "level_0"], "city column")
    grid_col = infer_column(
        flat,
        [
            "grid_index",
            "grid_number",
            "grid_num",
            "Grid_number",
            "Grid_Number",
            "grid",
            "Grid",
            "level_1",
            "index",
        ],
        "grid column",
    )
    out = flat[[city_col, grid_col, value_col]].copy()
    out.columns = ["city", "grid_index", output_value]
    out["grid_index"] = out["grid_index"].astype(int)
    return out


def require_columns(df: pd.DataFrame, columns: list[str], label: str) -> None:
    missing = [column for column in columns if column not in df.columns]
    if missing:
        raise KeyError(f"{label} is missing required columns: {missing}")


def read_city_main_case(root: Path) -> pd.DataFrame:
    city_path = FIG_INPUT_DIR / "main_case_city_totals.csv"
    if not city_path.exists():
        raise FileNotFoundError(
            f"Missing {city_path}. Download or regenerate the public inputs."
        )

    city = pd.read_csv(city_path)
    require_columns(
        city,
        [
            "City",
            "case_id",
            "rpv_installability",
            "fpv_installability_of_filtered_AOI",
            "rpv_capacity_GW",
            "fpv_capacity_GW",
            "fpv_generation_TWh",
            "fpv_carbon_Mt",
        ],
        city_path.name,
    )
    case_ids = set(city["case_id"].dropna().astype(str))
    if case_ids != {MAIN_CASE_ID}:
        raise ValueError(
            f"The city-level file is not the unique main case {MAIN_CASE_ID}: "
            f"found {sorted(case_ids)}"
        )
    if not np.allclose(city["rpv_installability"].to_numpy(float), 0.35):
        raise ValueError("The saved main case is not uniformly RPV=0.35.")
    if not np.allclose(
        city["fpv_installability_of_filtered_AOI"].to_numpy(float),
        MAIN_FPV_INSTALLABILITY,
    ):
        raise ValueError("The saved main case is not uniformly FPV=0.70.")
    if city["City"].duplicated().any():
        duplicated = city.loc[city["City"].duplicated(), "City"].tolist()
        raise ValueError(f"Duplicated cities in the main-case CSV: {duplicated}")
    return city


def read_zone_labels(root: Path) -> pd.DataFrame:
    path = FIG_INPUT_DIR / "nationwide_grid_zone_labels.csv"
    labels = pd.read_csv(path)
    require_columns(
        labels,
        [
            "city",
            "grid_index",
            "mean_height_m",
            "building_count_12m",
            "zone",
            "eligible_for_facade_model",
        ],
        path.name,
    )
    labels["grid_index"] = labels["grid_index"].astype(int)
    eligible = labels["eligible_for_facade_model"]
    if eligible.dtype != bool:
        eligible = eligible.astype(str).str.lower().isin(["true", "1", "yes"])
    labels["eligible_for_facade_model"] = eligible
    return labels


def build_grid_feature_label(fig_data_dir: Path) -> tuple[pd.DataFrame, list[str]]:
    static = read_hdf(fig_data_dir / "Grid_feas_static_all_df.h5")
    weather = read_hdf(fig_data_dir / "Grid_feas_wea_all_df.h5")
    capacity = read_hdf(fig_data_dir / "Cap_facade_ideal_all_df.h5")
    power = read_hdf(fig_data_dir / "Power_facade_ideal_1_sum_all_df.h5")
    grid_type = read_hdf(fig_data_dir / "Grid_type_all_df.h5")

    if static.shape[1] < 5:
        raise ValueError(
            "Grid_feas_static_all_df.h5 has too few columns to remove the four "
            "excluded fields (skew, WWR, can_avg, and can_std)."
        )
    require_columns(weather, ["Global"], "Grid_feas_wea_all_df.h5")
    require_columns(grid_type, ["facade_area"], "Grid_type_all_df.h5")

    cap_col = value_column(capacity, "Cap_facade_ideal", "Cap_facade_ideal_all_df.h5")
    power_col = value_column(
        power, "Power_facade_ideal_1_sum", "Power_facade_ideal_1_sum_all_df.h5"
    )

    feature_cols = list(static.iloc[:, :-4].columns) + ["Global"]
    frame = pd.concat(
        [
            static.iloc[:, :-4],
            weather[["Global"]],
            capacity[[cap_col]].rename(columns={cap_col: "Cap_facade_ideal"}),
            power[[power_col]].rename(columns={power_col: "Power_facade_ideal_1_sum"}),
        ],
        axis=1,
    )
    frame["Cap_facade_ideal"] *= FPV_MAIN_SCALE
    frame["Power_facade_ideal_1_sum"] *= FPV_MAIN_SCALE
    frame["util_hour"] = (
        frame["Power_facade_ideal_1_sum"] / frame["Cap_facade_ideal"] / 1e3
    )
    frame["generation_per_area"] = (
        frame["Power_facade_ideal_1_sum"] / grid_type["facade_area"] * 1e3
    )
    return frame, feature_cols


def validate_grid_generation_total(
    grid_frame: pd.DataFrame, city_main: pd.DataFrame
) -> None:
    grid_total_twh = grid_frame["Power_facade_ideal_1_sum"].sum() / 1e6
    city_total_twh = city_main["fpv_generation_TWh"].sum()
    if not np.isclose(grid_total_twh, city_total_twh, rtol=1e-5, atol=1e-5):
        raise ValueError(
            "Scaled grid generation does not match the city main case: "
            f"grid={grid_total_twh:.6f} TWh, city={city_total_twh:.6f} TWh. "
            "Check that the HDF baseline uses FPV=0.90 and that all inputs were "
            "generated from the same evaluation run."
        )


def fit_model_and_shap(
    frame: pd.DataFrame, feature_cols: list[str]
) -> tuple[pd.Series, float, float, float]:
    model_df = frame[feature_cols + ["Power_facade_ideal_1_sum"]].dropna()
    X = model_df[feature_cols]
    y = model_df["Power_facade_ideal_1_sum"] / 1e3

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    model = xgb.XGBRegressor(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.2,
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
    cv_rmse = rmse / float(np.mean(y_test))

    explainer = shap.TreeExplainer(model, X_train)
    shap_values = explainer.shap_values(X_test)
    importance = np.abs(shap_values).mean(axis=0)
    shap_series = pd.Series(importance, index=X_test.columns, dtype=float)

    name_map = {
        "lon": "Longitude",
        "lat": "Latitude",
        "density": "Building density",
        "hei_avg": "Mean building height",
        "hei_std": "Std. of building height",
        "area_std": "Std. of building footprint area",
        "complex": "Complexity",
        "compact": "Compactness",
        "volume": "Number of building volumes",
        "outdoor": "Mean outdoor distance",
        "12ratio": "12-ratio",
        "Global": "Annual gross radiation",
    }
    shap_series.index = [name_map.get(name, name) for name in shap_series.index]
    shap_series = shap_series.drop(labels=["12-ratio"], errors="ignore")
    shap_series /= shap_series.sum()
    return shap_series, r2, rmse, cv_rmse


def save_figure(fig: plt.Figure, pdf_path: Path) -> None:
    png_path = pdf_path.with_suffix(".png")
    fig.savefig(pdf_path, format="pdf", dpi=600, bbox_inches="tight")
    fig.savefig(png_path, format="png", dpi=600, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {pdf_path}")
    print(f"Saved {png_path}")


def draw_fig4a_1(shap_series: pd.Series, output_dir: Path) -> None:
    first_class = [
        "Building density",
        "Mean building height",
        "Std. of building height",
        "Std. of building footprint area",
        "Complexity",
        "Compactness",
        "Number of building volumes",
        "Mean outdoor distance",
    ]
    second_class = ["Longitude", "Latitude", "Annual gross radiation"]
    expected = first_class + second_class
    missing = [name for name in expected if name not in shap_series.index]
    if missing:
        raise KeyError(f"SHAP output is missing manuscript features: {missing}")
    shap_all = shap_series[expected].sort_values(ascending=False)

    plt.rc("font", size=FS - 3)
    fig, ax = plt.subplots(
        figsize=np.array([FIGWIDTH * 2 / 3, FIGWIDTH * 2 / 3 * 1.4]) / 2.54
    )
    positions = np.arange(len(shap_all))
    ax.barh(
        positions,
        shap_all.values,
        color="mediumseagreen",
        height=0.5,
        alpha=0.6,
    )
    ax.set_yticks([])
    ax.yaxis.tick_right()
    ax.set_xscale("log")
    ax.set_xlim(1e-3, 1)
    ax.set_ylim(-0.5, len(shap_all) - 0.5)
    ax.invert_yaxis()
    ax.set_xlabel("Importance", fontsize=FS)
    ax.set_ylabel("Feature", fontsize=FS)
    ax.tick_params(axis="y", length=0)
    for i, feature_name in enumerate(shap_all.index):
        ax.text(0.0012, i, feature_name, ha="left", va="center", fontsize=FS - 3)
    fig.subplots_adjust(left=0.08, right=0.96, bottom=0.10, top=0.98)
    save_figure(fig, output_dir / "Fig4a_1.pdf")


def draw_fig4a_2(frame: pd.DataFrame, output_dir: Path) -> None:
    plot_df = frame[["complex", "Power_facade_ideal_1_sum"]].dropna().copy()
    plot_df.sort_values("complex", inplace=True)
    x = plot_df["complex"].to_numpy()
    y = plot_df["Power_facade_ideal_1_sum"].to_numpy() / 1e3

    plt.rc("font", size=FS - 3)
    fig, ax = plt.subplots(
        figsize=np.array([FIGWIDTH * 2 / 3, FIGWIDTH * 2 / 3 * 0.7]) / 2.54
    )
    ax.scatter(x, y, color="mediumseagreen", s=20, alpha=0.8, edgecolors="none")
    ax.set_xlim(0, 1.5)
    ax.set_xticks(np.arange(0, 1.6, 0.3))
    ax.set_ylim(0, 200)
    ax.set_yticks(np.arange(0, 201, 50))
    ax.set_xlabel("Complexity (-)", fontsize=FS - 3)
    ax.set_ylabel("Annual generation (GWh)", fontsize=FS - 3)
    ax.grid(alpha=0.5)
    fig.subplots_adjust(left=0.19, right=0.96, bottom=0.18, top=0.96)
    save_figure(fig, output_dir / "Fig4a_2.pdf")


def draw_fig4a_3(
    root: Path, fig_data_dir: Path, labels: pd.DataFrame, output_dir: Path
) -> None:
    del root
    power = hdf_metric_with_grid_ids(
        fig_data_dir / "Power_facade_ideal_1_sum_all_df.h5",
        "Power_facade_ideal_1_sum",
        "power_baseline_MWh",
    )
    power["annual_generation_GWh"] = (
        power["power_baseline_MWh"] * FPV_MAIN_SCALE / 1e3
    )
    eligible = labels.loc[
        labels["eligible_for_facade_model"],
        ["city", "grid_index", "mean_height_m", "building_count_12m"],
    ]
    plot_df = eligible.merge(power, on=["city", "grid_index"], how="inner").dropna()
    if plot_df.empty:
        raise ValueError("No eligible grid rows matched the FPV power HDF for Fig. 4a_3.")

    generation = plot_df["annual_generation_GWh"].to_numpy()
    fig = plt.figure(
        figsize=np.array([FIGWIDTH * 2 / 3, FIGWIDTH * 2 / 3 * 0.7]) / 2.54
    )
    scatter = plt.scatter(
        plot_df["building_count_12m"],
        plot_df["mean_height_m"],
        s=np.maximum(generation, 0),
        c=generation,
        cmap="viridis",
        alpha=0.6,
        edgecolors="black",
        linewidth=0.5,
    )
    plt.xlim(-10, 6000)
    plt.ylim(10, 60)
    cbar = plt.colorbar(scatter)
    cbar.set_label("Annual generation (GWh)", fontsize=FS - 3)
    upper = max(1.0, float(np.nanmax(generation)))
    cbar.set_ticks(np.linspace(0, upper, 5))
    plt.xlabel("Building number", fontsize=FS - 3)
    plt.ylabel("Mean height (m)", fontsize=FS - 3)
    plt.grid(True, linestyle="--", alpha=0.3)
    plt.tight_layout()
    save_figure(fig, output_dir / "Fig4a_3.pdf")


def optimization_result_path(opt_results_dir: Path, city: str, city_index: int) -> Path:
    suffix = "_hybrid_n.mat" if city_index in ABNORMAL_VOLUME_CITY_INDICES else "_hybrid.mat"
    return opt_results_dir / f"{city}{suffix}"


def validate_optimization_arrays(
    city: str,
    grid_type: np.ndarray,
    r_pow_f: np.ndarray,
    r_car: np.ndarray,
    r_pow: np.ndarray,
    r_pow_buy: np.ndarray,
    r_car_t: np.ndarray,
) -> None:
    if grid_type.ndim != 2 or grid_type.shape[1] < 5:
        raise ValueError(
            f"{city}: Grid_type must be a 2-D array with at least five columns; shape={grid_type.shape}"
        )
    if r_pow_f.ndim != 4:
        raise ValueError(f"{city}: R_Pow_f must be 4-D; shape={r_pow_f.shape}")
    if r_car.ndim != 3 or r_car.shape[1] < 2:
        raise ValueError(f"{city}: R_Car must have shape [grid, 2, year]; shape={r_car.shape}")
    if r_pow.ndim != 4:
        raise ValueError(f"{city}: R_Pow must be 4-D; shape={r_pow.shape}")
    if r_pow_buy.ndim != 5 or r_pow_buy.shape[1] < 2:
        raise ValueError(f"{city}: R_Pow_Buy must have shape [grid, 2, year, day, hour]; shape={r_pow_buy.shape}")
    if r_car_t.ndim != 5 or r_car_t.shape[1] < 2:
        raise ValueError(f"{city}: R_Car_t must have shape [grid, 2, year, day, hour]; shape={r_car_t.shape}")
    n_grid = grid_type.shape[0]
    if any(arr.shape[0] != n_grid for arr in [r_pow_f, r_car, r_pow, r_pow_buy, r_car_t]):
        raise ValueError(
            f"{city}: grid counts disagree among Grid_type ({n_grid}), R_Pow_f ({r_pow_f.shape[0]}), "
            f"R_Car ({r_car.shape[0]}), R_Pow ({r_pow.shape[0]}), R_Pow_Buy ({r_pow_buy.shape[0]}), and R_Car_t ({r_car_t.shape[0]})."
        )
    if not (r_pow_f.shape[1] == r_car.shape[2] == r_pow.shape[1] == r_pow_buy.shape[2] == r_car_t.shape[2]):
        raise ValueError(f"{city}: planning-year counts disagree among saved MAT arrays.")


def _scale_to_saved_total(target: float, raw_total: float, city: str, label: str) -> float:
    target = float(target)
    raw_total = float(raw_total)
    if not np.isfinite(target) or target < 0:
        raise ValueError(f"{city}: invalid saved {label} target: {target}")
    if not np.isfinite(raw_total) or raw_total <= 0:
        if target == 0:
            return 0.0
        raise ValueError(f"{city}: invalid raw {label} total: {raw_total}")
    return target / raw_total


def _indices_non_zero_from_features(city: str, city_feature_dir: Path) -> np.ndarray:
    feature_path = city_feature_dir / f"{city}_ALL_Featuers.npy"
    if not feature_path.exists():
        raise FileNotFoundError(f"Missing {feature_path}")
    feature = np.load(feature_path)
    if feature.ndim != 2 or feature.shape[1] <= 11:
        raise ValueError(f"{city}: unexpected feature shape {feature.shape} in {feature_path}")
    return np.where(feature[:, 11] != 0)[0]


def _align_grid_level_arrays(
    city: str,
    grid_type: np.ndarray,
    cap_roof_raw: np.ndarray,
    cap_facade_raw: np.ndarray,
    city_feature_dir: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    len_grid = grid_type.shape[0]
    len_roof = cap_roof_raw.shape[0]
    len_facade = cap_facade_raw.shape[0]
    if len_grid == len_roof == len_facade:
        return grid_type, cap_roof_raw, cap_facade_raw

    idx_non_zero = _indices_non_zero_from_features(city, city_feature_dir)
    n_non_zero = len(idx_non_zero)

    if len_grid > n_non_zero:
        grid_type = grid_type[idx_non_zero]
        len_grid = grid_type.shape[0]
    if len_roof > n_non_zero:
        cap_roof_raw = cap_roof_raw[idx_non_zero]
        len_roof = cap_roof_raw.shape[0]
    if len_facade > n_non_zero:
        cap_facade_raw = cap_facade_raw[idx_non_zero]
        len_facade = cap_facade_raw.shape[0]

    if not (len_grid == len_roof == len_facade):
        raise ValueError(
            f"{city}: failed to align grid_type ({len_grid}), roof capacity ({len_roof}), and facade capacity ({len_facade})."
        )
    return grid_type, cap_roof_raw, cap_facade_raw


def _main_case_installable_areas(
    city: str,
    city_main_row: pd.Series,
    ml_results_dir: Path,
    city_feature_dir: Path,
    grid_type: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    capacity_dir = ml_results_dir / "Capacity"
    cap_roof_path = capacity_dir / f"Cap_roof_{city}.npy"
    cap_facade_path = capacity_dir / f"Cap_facade_{city}.npy"
    if not cap_roof_path.exists():
        raise FileNotFoundError(f"Missing {cap_roof_path}")
    if not cap_facade_path.exists():
        raise FileNotFoundError(f"Missing {cap_facade_path}")

    cap_roof_raw = np.asarray(np.load(cap_roof_path), dtype=float).reshape(-1)
    cap_facade_raw = np.asarray(np.load(cap_facade_path), dtype=float)
    if cap_facade_raw.ndim == 1:
        cap_facade_ideal = cap_facade_raw.reshape(-1)
    else:
        cap_facade_ideal = cap_facade_raw[:, -1].reshape(-1)

    grid_type, cap_roof_raw, cap_facade_ideal = _align_grid_level_arrays(
        city=city,
        grid_type=grid_type,
        cap_roof_raw=cap_roof_raw,
        cap_facade_raw=cap_facade_ideal,
        city_feature_dir=city_feature_dir,
    )

    roof_scale = _scale_to_saved_total(
        city_main_row["rpv_capacity_GW"], np.sum(cap_roof_raw), city, "RPV capacity"
    )
    facade_scale = _scale_to_saved_total(
        city_main_row["fpv_capacity_GW"], np.sum(cap_facade_ideal), city, "FPV capacity"
    )

    # Convert scaled capacity (GW) to equivalent installable PV area (m2) with
    # one common nominal density so that roof and facade use a consistent area definition.
    roof_area_eq = cap_roof_raw * roof_scale * 1e9 / PV_POWER_DENSITY_W_M2
    facade_area_eq = cap_facade_ideal * facade_scale * 1e9 / PV_POWER_DENSITY_W_M2
    return grid_type, roof_area_eq, facade_area_eq


def _infer_city_year_carbon_factors(r_car_t: np.ndarray, r_pow_buy: np.ndarray) -> np.ndarray:
    n_years = r_car_t.shape[2]
    factors = np.zeros(n_years, dtype=float)
    for y in range(n_years):
        den = np.sum(r_pow_buy[:, 0, y, :, :])
        if den <= 0:
            den = np.sum(r_pow_buy[:, 1, y, :, :])
            num = np.sum(r_car_t[:, 1, y, :, :])
        else:
            num = np.sum(r_car_t[:, 0, y, :, :])
        if den <= 0:
            raise ValueError(f"Cannot infer carbon factor for planning year index {y}: non-positive purchased electricity.")
        factors[y] = num / den
    return factors


def build_optimized_zone_pie_data(
    city_main: pd.DataFrame,
    ml_results_dir: Path,
    opt_results_dir: Path,
    cluster_days_path: Path,
    city_feature_dir: Path,
) -> pd.DataFrame:
    city_stat_path = ml_results_dir / "City_statistic.xlsx"
    grid_type_dir = ml_results_dir / "Grid_type"
    if not city_stat_path.exists():
        raise FileNotFoundError(f"Missing {city_stat_path}")
    if not opt_results_dir.exists():
        raise FileNotFoundError(f"Missing optimization directory: {opt_results_dir}")
    if not cluster_days_path.exists():
        raise FileNotFoundError(f"Missing {cluster_days_path}")

    city_stat = pd.read_excel(city_stat_path, sheet_name="Class_Volume", index_col=0)
    cities = city_stat.index.astype(str).str.strip().tolist()
    city_main = city_main.copy()
    city_main["City"] = city_main["City"].astype(str).str.strip()
    city_main = city_main.set_index("City")
    missing_main = sorted(set(cities).difference(city_main.index))
    extra_main = sorted(set(city_main.index).difference(cities))
    if missing_main or extra_main:
        raise ValueError(
            "City lists disagree between City_statistic.xlsx and the main-case CSV. "
            f"Missing in CSV={missing_main}; extra in CSV={extra_main}"
        )

    cluster_days = np.load(cluster_days_path)
    if cluster_days.ndim != 2 or cluster_days.shape[0] < len(cities):
        raise ValueError(
            f"Clu_days has incompatible shape {cluster_days.shape} for {len(cities)} cities."
        )

    zone_data = pd.DataFrame(
        0.0,
        index=ZONE_ORDER,
        columns=[
            "facade_area",
            "roof_area",
            "fpv_carbon_mitigation_Mt",
            "rpv_carbon_mitigation_Mt",
        ],
    )
    result_files = []

    for city_index, city in enumerate(cities):
        grid_path = grid_type_dir / f"Grid_type_{city}.npy"
        result_path = optimization_result_path(opt_results_dir, city, city_index)
        if not grid_path.exists():
            raise FileNotFoundError(f"Missing {grid_path}")
        if not result_path.exists():
            raise FileNotFoundError(
                f"Missing {result_path}. Confirm that Multi_period_planning.py finished all cities."
            )

        grid_type = np.asarray(np.load(grid_path), dtype=float)
        data = loadmat(
            result_path,
            variable_names=["R_Pow_f", "R_Car", "R_Pow", "R_Pow_Buy", "R_Car_t"],
        )
        required_keys = ["R_Pow_f", "R_Car", "R_Pow", "R_Pow_Buy", "R_Car_t"]
        missing_keys = [key for key in required_keys if key not in data]
        if missing_keys:
            raise KeyError(f"{result_path} is missing arrays: {missing_keys}")
        r_pow_f = np.asarray(data["R_Pow_f"], dtype=float)
        r_car = np.asarray(data["R_Car"], dtype=float)
        r_pow = np.asarray(data["R_Pow"], dtype=float)
        r_pow_buy = np.asarray(data["R_Pow_Buy"], dtype=float)
        r_car_t = np.asarray(data["R_Car_t"], dtype=float)

        city_main_row = city_main.loc[city]
        grid_type, roof_area_eq, facade_area_eq = _main_case_installable_areas(
            city=city,
            city_main_row=city_main_row,
            ml_results_dir=ml_results_dir,
            city_feature_dir=city_feature_dir,
            grid_type=grid_type,
        )

        validate_optimization_arrays(city, grid_type, r_pow_f, r_car, r_pow, r_pow_buy, r_car_t)

        n_typical_days = r_pow_f.shape[2]
        if cluster_days.shape[1] < n_typical_days:
            raise ValueError(
                f"{city}: Clu_days has {cluster_days.shape[1]} columns but R_Pow_f has {n_typical_days} representative days."
            )

        fpv_carbon_grid = np.sum(r_car[:, 0, :], axis=1) - np.sum(r_car[:, 1, :], axis=1)

        carbon_factor_y = _infer_city_year_carbon_factors(r_car_t, r_pow_buy)
        baseline_carbon_grid = np.zeros(grid_type.shape[0], dtype=float)
        for y in range(r_pow.shape[1]):
            load_y = np.zeros(grid_type.shape[0], dtype=float)
            for d in range(n_typical_days):
                load_y += 5 * cluster_days[city_index, d] * np.sum(r_pow[:, y, d, :], axis=1)
            baseline_carbon_grid += carbon_factor_y[y] * load_y
        rpv_carbon_grid = baseline_carbon_grid - np.sum(r_car[:, 0, :], axis=1)

        valid = np.where(grid_type[:, 0] != 888)[0]
        height = grid_type[valid, 1]
        building_count = grid_type[valid, 3]
        zone_masks = {
            "HnD": (height >= 18) & (building_count >= 200),
            "HnS": (height >= 18) & (building_count < 200),
            "MnD": (height < 18) & (building_count >= 200),
            "MnS": (height < 18) & (building_count < 200),
        }

        for zone, mask in zone_masks.items():
            grid_indices = valid[mask]
            zone_data.loc[zone, "facade_area"] += np.sum(facade_area_eq[grid_indices])
            zone_data.loc[zone, "roof_area"] += np.sum(roof_area_eq[grid_indices])
            zone_data.loc[zone, "fpv_carbon_mitigation_Mt"] += np.sum(fpv_carbon_grid[grid_indices])
            zone_data.loc[zone, "rpv_carbon_mitigation_Mt"] += np.sum(rpv_carbon_grid[grid_indices])

        result_files.append(result_path)
        print(f"Loaded optimized pathway: {city} ({city_index + 1}/{len(cities)})")

    if (zone_data.sum(axis=0) <= 0).any():
        raise ValueError(f"Optimization aggregation produced non-positive totals:\n{zone_data}")

    newest = max(path.stat().st_mtime for path in result_files)
    oldest = min(path.stat().st_mtime for path in result_files)
    print(
        f"Optimization source: {opt_results_dir} | files={len(result_files)} | "
        f"mtime range={pd.to_datetime(oldest, unit='s')} to {pd.to_datetime(newest, unit='s')}"
    )
    return zone_data


def draw_fig4b(zone_data: pd.DataFrame, output_dir: Path) -> None:
    values = zone_data[
        [
            "facade_area",
            "roof_area",
            "fpv_carbon_mitigation_Mt",
            "rpv_carbon_mitigation_Mt",
        ]
    ].to_numpy(dtype=float)
    ratios = 100 * values / values.sum(axis=0, keepdims=True)

    pie_titles = [
        "Facade Area",
        "Roof Area",
        "FPV carbon mitigation",
        "RPV carbon mitigation",
    ]

    plt.rc("font", size=FS - 8)
    fig, axes = plt.subplots(2, 2, figsize=np.array([FIGWIDTH * 0.95, FIGWIDTH * 1.05]) / 2.54)
    axes = axes.ravel()
    wedges = None

    for i, ax in enumerate(axes):
        # \u5de6\u4fa7\u4e24\u56fe\u7a81\u51fa HnD；\u53f3\u4fa7\u4e24\u56fe\u7a81\u51fa MnD
        highlight_idx = 2 if i in (1, 3) else 0

        explode = [0, 0, 0, 0]
        explode[highlight_idx] = 0.08

        wedges, _, _ = ax.pie(
            ratios[:, i],
            colors=ZONE_COLORS,
            autopct="%1.1f%%",
            startangle=90,
            textprops={"fontsize": FS - 10},
            pctdistance=0.62,
            radius=1.08,
            shadow=False,
            explode=explode,
        )

        ax.set_title(
            pie_titles[i],
            fontsize=FS - 3,
            fontweight="bold",
        )

        for j, wedge in enumerate(wedges):
            wedge.set_alpha(1.0 if j == highlight_idx else 0.85)
            if j == highlight_idx:
                wedge.set_edgecolor("blue")
                wedge.set_linewidth(1.2)
            else:
                wedge.set_edgecolor("white")
                wedge.set_linewidth(0.8)

    fig.subplots_adjust(
        wspace=0.15,
        hspace=0.10,
        bottom=0.11,
    )

    # \u5355\u72ec\u521b\u5efa\u4e2d\u6027\u7684\u56fe\u4f8b，\u4e0d\u7a81\u51fa\u663e\u793a HnD \u6216\u5176\u4ed6\u7c7b\u578b
    legend_handles = [
        Patch(
            facecolor=color,
            edgecolor="none",
            alpha=0.85,
            label=zone,
        )
        for zone, color in zip(ZONE_ORDER, ZONE_COLORS)
    ]

    fig.legend(
        handles=legend_handles,
        labels=ZONE_ORDER,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.055),
        ncol=4,
        fontsize=FS - 8,
    )
    save_figure(fig, output_dir / "Fig4b.pdf")

    summary = 100 * zone_data.div(zone_data.sum(axis=0), axis=1)
    print("Optimized-pathway Fig. 4b shares (%):")
    print(summary.round(1).to_string())


args = parse_args()
root = args.root.resolve()
figures_dir = SCRIPT_DIR
fig_data_dir = FIG_INPUT_DIR
output_dir = (
    args.output_dir.resolve() if args.output_dir is not None else figures_dir / "Figs_new"
)
output_dir.mkdir(parents=True, exist_ok=True)
setup_style(figures_dir)

city_main = read_city_main_case(root)
labels = read_zone_labels(root)
grid_frame, feature_cols = build_grid_feature_label(fig_data_dir)
validate_grid_generation_total(grid_frame, city_main)

shap_series, r2, rmse, cv_rmse = fit_model_and_shap(grid_frame, feature_cols)
print(f"Test R^2: {r2:.3f}")
print(f"Test RMSE: {rmse:.3f} GWh")
print(f"Test CV-RMSE: {cv_rmse * 100:.2f}%")

draw_fig4a_1(shap_series, output_dir)
draw_fig4a_2(grid_frame, output_dir)
draw_fig4a_3(root, fig_data_dir, labels, output_dir)
cluster_days_path = (
    args.cluster_days.resolve() if args.cluster_days is not None else fig_data_dir / "Clu_days.npy"
)
zone_cache_path = fig_data_dir / "Fig4b_zone_data.csv"
if zone_cache_path.exists():
    optimized_zone_data = pd.read_csv(zone_cache_path, index_col=0)
    optimized_zone_data = optimized_zone_data.reindex(ZONE_ORDER)
else:
    optimized_zone_data = build_optimized_zone_pie_data(
        city_main=city_main,
        ml_results_dir=args.ml_results_dir.resolve(),
        opt_results_dir=args.opt_results_dir.resolve(),
        cluster_days_path=cluster_days_path,
        city_feature_dir=args.city_feature_dir.resolve(),
    )
    optimized_zone_data.to_csv(zone_cache_path)
draw_fig4b(optimized_zone_data, output_dir)
